// Generated by Wrangler by running `wrangler types`

import type { PrismaClient } from "@prisma/client";

export interface Env {
	db: D1Database;
}
export interface Context {
	prisma: PrismaClient;
}
